const C=window.M4X_CONFIG||{};
const sb=(C.SUPABASE_URL&&C.SUPABASE_ANON_KEY)?supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY):null;
const S={session:null,profile:null,tab:'home',themes:[],config:{},admin:false};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m){let x=document.createElement('div');x.className='toast';x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),3200)}
function money(n){return new Intl.NumberFormat('vi-VN').format(Number(n||0))}
async function q(table,opts={}){let r=sb.from(table).select(opts.select||'*');if(opts.eq)Object.entries(opts.eq).forEach(([k,v])=>r=r.eq(k,v));if(opts.order)r=r.order(opts.order,{ascending:!!opts.asc});if(opts.limit)r=r.limit(opts.limit);let {data,error}=await r;if(error)throw error;return data||[]}
async function rpc(name,args={}){let {data,error}=await sb.rpc(name,args);if(error)throw error;return data}
async function boot(){if(!sb){$('#app').innerHTML='<div class="splash"><h2>Chưa cấu hình Supabase</h2><p>Kiểm tra GitHub Secrets và workflow Deploy.</p></div>';return}let {data}=await sb.auth.getSession();S.session=data.session;if(S.session)await loadUser();render();sb.auth.onAuthStateChange(async(_,ses)=>{S.session=ses;if(ses)await loadUser();else{S.profile=null;S.admin=false}render()})}
async function loadUser(){try{let p=await q('profiles',{eq:{id:S.session.user.id},limit:1});S.profile=p[0]||null;S.admin=['admin','super_admin'].includes(S.profile?.role);let a=await q('app_config',{limit:1});S.config=a[0]||{};S.themes=await q('themes',{eq:{status:'approved'},order:'created_at'}); }catch(e){toast(e.message)}}
function shell(body){return `<header class="top"><img class="logo" src="icon.png"><div><h1>M4X Theme</h1><div class="sub">M4X COIN • Online v${esc(C.WEB_VERSION||'4')}</div></div><div class="coins">◉ ${money(S.profile?.points)}</div></header><main class="content">${body}</main><nav class="nav">${[['home','⌂','Khám phá'],['quest','◫','Nhiệm vụ'],['upload','⊕','Đăng'],['web','◉','M4X WEB'],['profile','♟','Hồ sơ']].map(x=>`<button class="${S.tab===x[0]?'on':''}" onclick="go('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}</nav>`}
function render(){if(!S.session){authView();return}let body={home:homeView,quest:questView,upload:uploadView,web:webView,profile:profileView}[S.tab]();$('#app').innerHTML=shell(body);if(S.tab==='quest')loadQuestData();if(S.tab==='profile')loadProfileData()}
window.go=t=>{S.tab=t;render()}
function authView(){$('#app').innerHTML=`<div class="splash" style="padding:24px"><img src="icon.png"><h1>M4X Theme</h1><div class="card" style="width:min(430px,92vw)"><input id="email" placeholder="Email"><input id="pass" type="password" placeholder="Mật khẩu"><input id="name" placeholder="Tên hiển thị (khi đăng ký)"><div class="row"><button onclick="login()">Đăng nhập</button><button class="secondary" onclick="signup()">Đăng ký</button></div></div><p class="muted">Ứng dụng OTA online hoàn toàn</p></div>`}
window.login=async()=>{try{let {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#pass').value});if(error)throw error}catch(e){toast(e.message)}}
window.signup=async()=>{try{let name=$('#name').value.trim();let {error}=await sb.auth.signUp({email:$('#email').value,password:$('#pass').value,options:{data:{display_name:name,username:name.toLowerCase().replace(/\s+/g,'_')}}});if(error)throw error;toast('Đăng ký thành công, hãy kiểm tra email nếu được yêu cầu')}catch(e){toast(e.message)}}
function homeView(){return `<section class="card hero"><span class="badge">M4X UNIVERSE • FULL OTA</span><h2>${esc(S.config.home_banner_title||'Kho Theme Xiaomi')}</h2><p>${esc(S.config.home_banner_subtitle||'HyperOS • MIUI • cập nhật online')}</p></section><div class="section-title"><h2>Theme mới cập nhật</h2><button class="secondary" onclick="reload()">↻ Làm mới</button></div><section class="grid">${S.themes.map(t=>`<article class="theme" onclick="themeDetail('${t.id}')"><img src="${esc(t.preview_url||'icon.png')}" onerror="this.src='icon.png'"><div class="p"><h3>${esc(t.title)}</h3><div class="muted">⬇ ${money(t.downloads)} • ◉ ${money(t.coin_price)}</div></div></article>`).join('')||'<p>Chưa có theme được duyệt.</p>'}</section>`}
window.reload=async()=>{await loadUser();render();toast('Đã cập nhật dữ liệu online')}
window.themeDetail=async id=>{let t=S.themes.find(x=>x.id===id);if(!t)return;let pics=Array.isArray(t.preview_urls)?t.preview_urls:[t.preview_url].filter(Boolean);let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="card"><button class="secondary" onclick="this.closest('.modal').remove()">✕</button><h2>${esc(t.title)}</h2>${pics.map(p=>`<img src="${esc(p)}" style="width:100%;border-radius:18px;margin:8px 0">`).join('')}<p>${esc(t.description)}</p><p>Giá: <b>${money(t.coin_price)} M4X COIN</b></p><button onclick="buyTheme('${t.id}')">Mua / Tải theme</button></div>`;document.body.append(m)}
window.buyTheme=async id=>{try{await rpc('purchase_theme',{theme_id:id});let t=S.themes.find(x=>x.id===id);await rpc('increment_theme_download',{theme_id:id});window.open(t.drive_url||t.file_url,'_blank');toast('Đã mở link tải theme')}catch(e){toast(e.message)}}
function questView(){return `<section class="card chest"><div class="chest-icon">🎁</div><h2>Mở Rương M4X</h2><p>Tốn 20 coin • phần thưởng tối đa 3.500 coin</p><button onclick="openChest()">MỞ RƯƠNG • 20 COIN</button><p class="muted">Cờ bạc là bác thằng bần.</p></section><section class="card"><h2>Nhiệm vụ</h2><div id="quests">Đang tải…</div></section><section class="card"><h2>Top đóng góp tuần</h2><div id="ranks">Đang tải…</div></section>`}
async function loadQuestData(){try{let qs=await q('quests',{eq:{active:true},order:'created_at'});$('#quests').innerHTML=qs.map(x=>`<div class="listitem"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.description)} • +${money(x.reward)}</div></div><button onclick="claimQuest('${x.id}')">Nhận</button></div>`).join('')||'Không còn nhiệm vụ.';let rs=await q('weekly_scores',{order:'score',limit:10});$('#ranks').innerHTML=rs.map((x,i)=>`<div class="listitem"><span class="rank">#${i+1}</span><div><b>${esc(x.display_name||x.user_id)}</b><div class="muted">Theme ${x.approved_themes||0} • Tải ${x.downloads_received||0} • ${x.active_minutes||0} phút</div></div><b>${money(x.score)} điểm</b></div>`).join('')||'Đang cập nhật online.'}catch(e){toast(e.message)}}
window.openChest=async()=>{try{let r=await rpc('open_coin_chest');toast((r?.message||'Đã mở rương')+(r?.reward?` +${r.reward} coin`:''));await loadUser();render()}catch(e){toast(e.message)}}
window.claimQuest=async id=>{try{await rpc('claim_quest',{quest_id:id});toast('Đã nhận thưởng');await loadUser();render()}catch(e){toast(e.message)}}
function uploadView(){return `<section class="card"><h2>Đăng theme</h2><input id="utitle" placeholder="Tên theme"><textarea id="udesc" placeholder="Mô tả"></textarea><div class="row"><select id="ucat"><option>HyperOS</option><option>MIUI</option><option>Lockscreen</option></select><input id="ucoin" type="number" min="0" placeholder="Giá coin"></div><input id="udrive" placeholder="Link Google Drive (cho file lớn)"><label>File .mtz/.zip</label><input id="ufile" type="file" accept=".mtz,.zip"><label>Ảnh xem trước (tối đa 5)</label><input id="upreview" type="file" accept="image/*" multiple><button onclick="uploadTheme()">Gửi theme chờ duyệt</button><div id="upstatus" class="muted"></div></section>`}
async function storeFile(file,path){let {error}=await sb.storage.from('themes').upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from('themes').getPublicUrl(path).data.publicUrl}
window.uploadTheme=async()=>{let st=$('#upstatus');try{st.textContent='Đang tải lên…';let uid=S.session.user.id, file=$('#ufile').files[0], previews=[...$('#upreview').files].slice(0,5), drive=$('#udrive').value.trim();if(!file&&!drive)throw Error('Chọn file hoặc nhập link Drive');let fileUrl='';if(file)fileUrl=await storeFile(file,`${uid}/files/${Date.now()}_${file.name}`);let pics=[];for(let i=0;i<previews.length;i++)pics.push(await storeFile(previews[i],`${uid}/previews/${Date.now()}_${i}_${previews[i].name}`));let {error}=await sb.from('themes').insert({owner_id:uid,title:$('#utitle').value.trim(),description:$('#udesc').value.trim(),category:$('#ucat').value,os_version:$('#ucat').value,file_url:fileUrl,drive_url:drive,preview_url:pics[0]||'',preview_urls:pics,status:'pending',coin_price:Number($('#ucoin').value||0)});if(error)throw error;st.textContent='Đã gửi, chờ Admin duyệt.';toast('Đăng theme thành công')}catch(e){st.textContent=e.message;toast(e.message)}}
function webView(){let items=[['⚽','Xem Đá Bóng','web_football_url','web_football_enabled'],['🎬','Xem phim','web_movie_url','web_movie_enabled'],['🔞','Xem 18+','web_adult_url','web_adult_enabled']];return `<section class="card hero" style="min-height:145px"><span class="badge">TRÌNH DUYỆT RIÊNG TƯ</span><h2>M4X WEB</h2><p>Khi mở chỉ hiển thị nội dung web toàn màn hình.</p></section>${items.filter(x=>S.config[x[3]]!==false).map(x=>`<div class="card feature-card" onclick="openWeb('${esc(S.config[x[2]]||'')}','${x[1]}')"><div class="feature-icon">${x[0]}</div><div><h3>${x[1]}</h3><span class="muted">Chạm để mở</span></div></div>`).join('')}${S.admin?'<button onclick="adminWeb()">Quản lý link M4X WEB</button>':''}`}
window.openWeb=(url,title)=>{if(!url)return toast('Tác vụ chưa có link');if(title.includes('18+')&&!confirm('Bạn xác nhận đã đủ 18 tuổi?'))return;let x=document.createElement('div');x.className='webfull';x.innerHTML=`<button class="webback" onclick="this.parentElement.remove()">←</button><iframe allow="autoplay; fullscreen; picture-in-picture" allowfullscreen src="${esc(url)}"></iframe>`;document.body.append(x)}
window.adminWeb=()=>{let f=document.createElement('div');f.className='modal';f.innerHTML=`<div class="card"><h2>Admin • M4X WEB</h2>${[['Bóng đá','football'],['Phim','movie'],['18+','adult']].map(x=>`<label>${x[0]}</label><input id="aw_${x[1]}" value="${esc(S.config['web_'+x[1]+'_url']||'')}"><label><input style="width:auto" type="checkbox" id="ae_${x[1]}" ${S.config['web_'+x[1]+'_enabled']!==false?'checked':''}> Bật tác vụ</label>`).join('')}<div class="row"><button onclick="saveWeb()">Lưu online</button><button class="secondary" onclick="this.closest('.modal').remove()">Đóng</button></div></div>`;document.body.append(f)}
window.saveWeb=async()=>{try{let patch={};['football','movie','adult'].forEach(k=>{patch['web_'+k+'_url']=$('#aw_'+k).value;patch['web_'+k+'_enabled']=$('#ae_'+k).checked});let id=S.config.id;let r=id?sb.from('app_config').update(patch).eq('id',id):sb.from('app_config').insert(patch);let {error}=await r;if(error)throw error;document.querySelector('.modal')?.remove();await loadUser();render();toast('Đã cập nhật link online')}catch(e){toast(e.message)}}
function profileView(){return `<section class="card profile-head"><div class="avatar">${esc((S.profile?.display_name||S.profile?.username||'M').charAt(0).toUpperCase())}</div><h2>${esc(S.profile?.display_name||S.profile?.username)}</h2><p class="muted">@${esc(S.profile?.username)} • ${esc(S.profile?.role)}</p><div class="statline"><div class="stat"><b>${money(S.profile?.points)}</b><span>M4X COIN</span></div><div class="stat"><b>OTA</b><span>ONLINE</span></div><div class="stat"><b>${S.admin?'ADMIN':'MEMBER'}</b><span>VAI TRÒ</span></div></div><br><button class="secondary" onclick="redeem()">🎟 Nhập Giftcode</button></section><section class="card"><h2>Giới thiệu</h2><p>Kênh Telegram M4X Theme Store</p><button onclick="window.open('https://t.me/m4xthemestore','_blank')">Mở Telegram</button></section><section class="card"><h2>Phiên bản Online</h2><p>Web v${esc(C.WEB_VERSION||'4.0.0')}</p><p class="muted">Mỗi lần Admin cập nhật GitHub Pages, người dùng chỉ cần mở lại app.</p><button onclick="location.reload(true)">Tải bản online mới nhất</button></section>${S.admin?'<section class="card"><h2>Trung tâm Admin</h2><button onclick="adminPanel()">Mở quản trị</button></section>':''}<button class="danger" onclick="logout()">Đăng xuất</button><div id="pdata"></div>`}
async function loadProfileData(){try{let my=await q('themes',{eq:{owner_id:S.session.user.id},order:'created_at'});let el=$('#pdata');if(el)el.innerHTML=`<section class="card"><h2>Theme của tôi</h2>${my.map(x=>`<div class="listitem"><div><b>${esc(x.title)}</b><div class="muted">${esc(x.status)} • ${money(x.downloads)} lượt tải</div></div></div>`).join('')||'Chưa đăng theme.'}</section>`}catch(e){}}
window.redeem=async()=>{let c=prompt('Nhập giftcode');if(!c)return;try{await rpc('redeem_giftcode',{gift_code:c});toast('Nhận giftcode thành công');await loadUser();render()}catch(e){toast(e.message)}}
window.logout=()=>sb.auth.signOut()
window.adminPanel=async()=>{try{let pending=await q('themes',{eq:{status:'pending'},order:'created_at'});let users=await q('profiles',{order:'created_at',limit:50});let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="card"><button class="secondary" onclick="this.closest('.modal').remove()">Đóng</button><h2>Theme chờ duyệt</h2>${pending.map(t=>`<div class="listitem"><div><b>${esc(t.title)}</b><div class="muted">${esc(t.description)}</div></div><button onclick="approve('${t.id}',true)">Duyệt</button><button class="danger" onclick="approve('${t.id}',false)">Từ chối</button></div>`).join('')||'Không có theme chờ.'}<h2>Thành viên</h2>${users.map(u=>`<div class="listitem"><div><b>${esc(u.display_name||u.username)}</b><div class="muted">${esc(u.role)} • ${money(u.points)} coin</div></div></div>`).join('')}</div>`;document.body.append(m)}catch(e){toast(e.message)}}
window.approve=async(id,ok)=>{try{let patch={status:ok?'approved':'rejected',reject_reason:ok?'':(prompt('Lý do từ chối')||'Không đạt yêu cầu')};let {error}=await sb.from('themes').update(patch).eq('id',id);if(error)throw error;document.querySelector('.modal')?.remove();toast(ok?'Đã duyệt':'Đã từ chối');adminPanel()}catch(e){toast(e.message)}}
boot();
